[tool.poetry]
name = "custom-library"
version = "0.1.0"
description = ""
authors = ["Oscar-Gomez <oscar.gomez@coxautoinc.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
